version: '3'
services:
  application:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      -   database
    environment:
      - DATABASE_URL=postgres://dice:dicepassword@database:5432/dice
  database:
    image: postgres:12
    environment:
      - POSTGRES_USER=dice
      - POSTGRES_PASSWORD=dicepassword
      - POSTGRES_DB=dice
